baseurl = "https://f3l1x.io/"
languageCode = "en-us"
title = "Milan Felix Å ulc - Developer"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[params]
    github = "https://github.com/f3l1x/f3l1x/"
    github_content = "https://github.com/f3l1x/f3l1x/blob/master/content/"
